/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/minio/minio-operator/pkg/apis/miniocontroller/v1beta1"
	scheme "github.com/minio/minio-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MinIOInstancesGetter has a method to return a MinIOInstanceInterface.
// A group's client should implement this interface.
type MinIOInstancesGetter interface {
	MinIOInstances(namespace string) MinIOInstanceInterface
}

// MinIOInstanceInterface has methods to work with MinIOInstance resources.
type MinIOInstanceInterface interface {
	Create(*v1beta1.MinIOInstance) (*v1beta1.MinIOInstance, error)
	Update(*v1beta1.MinIOInstance) (*v1beta1.MinIOInstance, error)
	UpdateStatus(*v1beta1.MinIOInstance) (*v1beta1.MinIOInstance, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.MinIOInstance, error)
	List(opts v1.ListOptions) (*v1beta1.MinIOInstanceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.MinIOInstance, err error)
	MinIOInstanceExpansion
}

// minIOInstances implements MinIOInstanceInterface
type minIOInstances struct {
	client rest.Interface
	ns     string
}

// newMinIOInstances returns a MinIOInstances
func newMinIOInstances(c *MinV1beta1Client, namespace string) *minIOInstances {
	return &minIOInstances{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the minIOInstance, and returns the corresponding minIOInstance object, and an error if there is any.
func (c *minIOInstances) Get(name string, options v1.GetOptions) (result *v1beta1.MinIOInstance, err error) {
	result = &v1beta1.MinIOInstance{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("minioinstances").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MinIOInstances that match those selectors.
func (c *minIOInstances) List(opts v1.ListOptions) (result *v1beta1.MinIOInstanceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.MinIOInstanceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("minioinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested minIOInstances.
func (c *minIOInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("minioinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a minIOInstance and creates it.  Returns the server's representation of the minIOInstance, and an error, if there is any.
func (c *minIOInstances) Create(minIOInstance *v1beta1.MinIOInstance) (result *v1beta1.MinIOInstance, err error) {
	result = &v1beta1.MinIOInstance{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("minioinstances").
		Body(minIOInstance).
		Do().
		Into(result)
	return
}

// Update takes the representation of a minIOInstance and updates it. Returns the server's representation of the minIOInstance, and an error, if there is any.
func (c *minIOInstances) Update(minIOInstance *v1beta1.MinIOInstance) (result *v1beta1.MinIOInstance, err error) {
	result = &v1beta1.MinIOInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("minioinstances").
		Name(minIOInstance.Name).
		Body(minIOInstance).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *minIOInstances) UpdateStatus(minIOInstance *v1beta1.MinIOInstance) (result *v1beta1.MinIOInstance, err error) {
	result = &v1beta1.MinIOInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("minioinstances").
		Name(minIOInstance.Name).
		SubResource("status").
		Body(minIOInstance).
		Do().
		Into(result)
	return
}

// Delete takes name of the minIOInstance and deletes it. Returns an error if one occurs.
func (c *minIOInstances) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("minioinstances").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *minIOInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("minioinstances").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched minIOInstance.
func (c *minIOInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.MinIOInstance, err error) {
	result = &v1beta1.MinIOInstance{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("minioinstances").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
