apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: minio-operator
spec:
  template:
    spec:
      containers:
        - name: console
          env:
          - name: CONSOLE_IDP_URL
            value: https://myidpserver.com/realms/realmname/.well-known/openid-configuration
          - name: CONSOLE_IDP_CLIENT_ID
            value: "" # Client registered in Open ID
          - name: CONSOLE_IDP_SECRET
            value: "" #Client secret in Open ID
          - name: CONSOLE_IDP_CALLBACK_DYNAMIC
            value: "on"
          volumeMounts:
            - mountPath: /tmp/certs/CAs
              name: idp-certificate
      volumes:
        - name: idp-certificate
          projected:
            sources:
              - secret:
                  items:
                    - key: ca.crt
                      path: idp.crt
                  name: idp-ca-tls
