apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: operator-tls
    service.beta.openshift.io/serving-cert-secret-name: operator-tls
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/name: operator
    name: minio-operator
  name: operator
spec:
  ports:
  - name: https
    port: 4222
    targetPort: 0
  - name: http
    port: 4221
    targetPort: 0
  selector:
    name: minio-operator
    operator: leader
  type: ClusterIP
status:
  loadBalancer: {}
