apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: tenant-tiny
patchesStrategicMerge:
  - tenant.yaml
patchesJson6902:
  - target:
      group: minio.min.io
      version: v2
      kind: Tenant
      name: storage
    path: tenantNamePatch.yaml