apiVersion: v1
kind: ConfigMap
metadata:
  name: start-config-script
  namespace: minio-tenant-1
data:
  setup.sh: |
    #!/bin/bash
    mc mb local/test-bucket -p && \
    mc mb local/other-bucket -p && \
    mc admin policy create local test-bucket-rw /start-config/bucket-policy.json
  bucket-policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "s3:*"
          ],
          "Resource": [
            "arn:aws:s3:::test-bucket",
            "arn:aws:s3:::test-bucket/*"
          ]
        }
      ]
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-bucket
  namespace: minio-tenant-1
spec:
  backoffLimit: 5
  template:
    spec:
      serviceAccountName: mc-job-sa
      restartPolicy: OnFailure
      volumes:
        - name: start-config
          configMap:
            name: start-config-script
            defaultMode: 0744
      containers:
        - name: mc
          image: minio/mc
          command: [ "/start-config/setup.sh" ]
          volumeMounts:
            - name: start-config
              mountPath: /start-config/
          env:
            - name: MC_HOST_local
              value: https://$(ACCESS_KEY):$(SECRET_KEY)@minio.minio-tenant-1.svc.cluster.local
            - name: MC_STS_ENDPOINT
              value: https://sts.minio-operator.svc.cluster.local:4223/sts/minio-tenant-1
            - name: MC_WEB_IDENTITY_TOKEN_FILE
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
