{{- if dig "tenant" "kes" "configuration" false (.Values | merge (dict)) }}
apiVersion: v1
kind: Secret
metadata:
  name: kes-configuration
  namespace: {{ template "minio-tenant.namespace" $ }}
type: Opaque
stringData:
  server-config.yaml: {{ .Values.tenant.kes.configuration | toYaml | indent 2 }}
{{- end }}
