{{ range .Values.tenants }}
{{- if dig "secrets" "enabled" false . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ dig "secrets" "name" "" . }}
  namespace: {{ .namespace }}
type: Opaque
data:
  ## Access Key for MinIO Tenant
  accesskey: {{ dig "secrets" "accessKey" "" . | b64enc }}
  ## Secret Key for MinIO Tenant
  secretkey: {{ dig "secrets" "secretKey" "" . | b64enc }}
{{- end }}
{{ end }}
