// This file is part of MinIO Operator
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	operatorminiov1 "github.com/minio/minio-operator/pkg/apis/operator.min.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMinIOInstances implements MinIOInstanceInterface
type FakeMinIOInstances struct {
	Fake *FakeOperatorV1
	ns   string
}

var minioinstancesResource = schema.GroupVersionResource{Group: "operator.min.io", Version: "v1", Resource: "minioinstances"}

var minioinstancesKind = schema.GroupVersionKind{Group: "operator.min.io", Version: "v1", Kind: "MinIOInstance"}

// Get takes name of the minIOInstance, and returns the corresponding minIOInstance object, and an error if there is any.
func (c *FakeMinIOInstances) Get(ctx context.Context, name string, options v1.GetOptions) (result *operatorminiov1.MinIOInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(minioinstancesResource, c.ns, name), &operatorminiov1.MinIOInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorminiov1.MinIOInstance), err
}

// List takes label and field selectors, and returns the list of MinIOInstances that match those selectors.
func (c *FakeMinIOInstances) List(ctx context.Context, opts v1.ListOptions) (result *operatorminiov1.MinIOInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(minioinstancesResource, minioinstancesKind, c.ns, opts), &operatorminiov1.MinIOInstanceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &operatorminiov1.MinIOInstanceList{ListMeta: obj.(*operatorminiov1.MinIOInstanceList).ListMeta}
	for _, item := range obj.(*operatorminiov1.MinIOInstanceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested minIOInstances.
func (c *FakeMinIOInstances) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(minioinstancesResource, c.ns, opts))

}

// Create takes the representation of a minIOInstance and creates it.  Returns the server's representation of the minIOInstance, and an error, if there is any.
func (c *FakeMinIOInstances) Create(ctx context.Context, minIOInstance *operatorminiov1.MinIOInstance, opts v1.CreateOptions) (result *operatorminiov1.MinIOInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(minioinstancesResource, c.ns, minIOInstance), &operatorminiov1.MinIOInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorminiov1.MinIOInstance), err
}

// Update takes the representation of a minIOInstance and updates it. Returns the server's representation of the minIOInstance, and an error, if there is any.
func (c *FakeMinIOInstances) Update(ctx context.Context, minIOInstance *operatorminiov1.MinIOInstance, opts v1.UpdateOptions) (result *operatorminiov1.MinIOInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(minioinstancesResource, c.ns, minIOInstance), &operatorminiov1.MinIOInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorminiov1.MinIOInstance), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMinIOInstances) UpdateStatus(ctx context.Context, minIOInstance *operatorminiov1.MinIOInstance, opts v1.UpdateOptions) (*operatorminiov1.MinIOInstance, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(minioinstancesResource, "status", c.ns, minIOInstance), &operatorminiov1.MinIOInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorminiov1.MinIOInstance), err
}

// Delete takes name of the minIOInstance and deletes it. Returns an error if one occurs.
func (c *FakeMinIOInstances) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(minioinstancesResource, c.ns, name), &operatorminiov1.MinIOInstance{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMinIOInstances) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(minioinstancesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &operatorminiov1.MinIOInstanceList{})
	return err
}

// Patch applies the patch and returns the patched minIOInstance.
func (c *FakeMinIOInstances) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operatorminiov1.MinIOInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(minioinstancesResource, c.ns, name, pt, data, subresources...), &operatorminiov1.MinIOInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorminiov1.MinIOInstance), err
}
