// This file is part of MinIO Console Server
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	operatorminiov1 "github.com/minio/minio-operator/pkg/apis/operator.min.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMirrorInstances implements MirrorInstanceInterface
type FakeMirrorInstances struct {
	Fake *FakeOperatorV1
	ns   string
}

var mirrorinstancesResource = schema.GroupVersionResource{Group: "operator.min.io", Version: "v1", Resource: "mirrorinstances"}

var mirrorinstancesKind = schema.GroupVersionKind{Group: "operator.min.io", Version: "v1", Kind: "MirrorInstance"}

// Get takes name of the mirrorInstance, and returns the corresponding mirrorInstance object, and an error if there is any.
func (c *FakeMirrorInstances) Get(ctx context.Context, name string, options v1.GetOptions) (result *operatorminiov1.MirrorInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mirrorinstancesResource, c.ns, name), &operatorminiov1.MirrorInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorminiov1.MirrorInstance), err
}

// List takes label and field selectors, and returns the list of MirrorInstances that match those selectors.
func (c *FakeMirrorInstances) List(ctx context.Context, opts v1.ListOptions) (result *operatorminiov1.MirrorInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mirrorinstancesResource, mirrorinstancesKind, c.ns, opts), &operatorminiov1.MirrorInstanceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &operatorminiov1.MirrorInstanceList{ListMeta: obj.(*operatorminiov1.MirrorInstanceList).ListMeta}
	for _, item := range obj.(*operatorminiov1.MirrorInstanceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mirrorInstances.
func (c *FakeMirrorInstances) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mirrorinstancesResource, c.ns, opts))

}

// Create takes the representation of a mirrorInstance and creates it.  Returns the server's representation of the mirrorInstance, and an error, if there is any.
func (c *FakeMirrorInstances) Create(ctx context.Context, mirrorInstance *operatorminiov1.MirrorInstance, opts v1.CreateOptions) (result *operatorminiov1.MirrorInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mirrorinstancesResource, c.ns, mirrorInstance), &operatorminiov1.MirrorInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorminiov1.MirrorInstance), err
}

// Update takes the representation of a mirrorInstance and updates it. Returns the server's representation of the mirrorInstance, and an error, if there is any.
func (c *FakeMirrorInstances) Update(ctx context.Context, mirrorInstance *operatorminiov1.MirrorInstance, opts v1.UpdateOptions) (result *operatorminiov1.MirrorInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mirrorinstancesResource, c.ns, mirrorInstance), &operatorminiov1.MirrorInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorminiov1.MirrorInstance), err
}

// Delete takes name of the mirrorInstance and deletes it. Returns an error if one occurs.
func (c *FakeMirrorInstances) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mirrorinstancesResource, c.ns, name), &operatorminiov1.MirrorInstance{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMirrorInstances) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mirrorinstancesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &operatorminiov1.MirrorInstanceList{})
	return err
}

// Patch applies the patch and returns the patched mirrorInstance.
func (c *FakeMirrorInstances) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operatorminiov1.MirrorInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mirrorinstancesResource, c.ns, name, pt, data, subresources...), &operatorminiov1.MirrorInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorminiov1.MirrorInstance), err
}
