---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-namespace: minio-operator
    meta.helm.sh/release-name: minio-operator
  name: policybindings.sts.min.io
  namespace: minio-operator