apiVersion: v1
kind: ServiceAccount
metadata:
  name: console-sa
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: console-sa-secret
  namespace: minio-operator
  annotations:
    kubernetes.io/service-account.name: console-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: console-sa-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch
      - create
      - list
      - patch
      - update
      - delete
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - namespaces
      - services
      - events
      - resourcequotas
      - nodes
    verbs:
      - get
      - watch
      - create
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - create
      - list
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - deletecollection
      - list
      - get
      - watch
      - update
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - watch
      - create
      - list
      - patch
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
    verbs:
      - get
      - create
      - list
      - patch
      - watch
      - update
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - create
      - list
      - patch
      - watch
      - update
      - delete
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
      - certificatesigningrequests/approval
      - certificatesigningrequests/status
    verbs:
      - update
      - create
      - get
      - delete
      - list
  - apiGroups:
      - minio.min.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - min.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
    verbs:
      - get
      - list
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotcontents
    verbs:
      - get
      - list
  - apiGroups:
      - storage.k8s.io
    resources:
      - csinodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - pod
      - pods/log
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-sa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: console-sa-role
subjects:
  - kind: ServiceAccount
    name: console-sa
    namespace: default
---
apiVersion: v1
data:
  CONSOLE_PORT: "9090"
  CONSOLE_TLS_PORT: "9443"
kind: ConfigMap
metadata:
  name: console-env
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: console
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/name: operator
  name: console
spec:
  ports:
    - name: http
      port: 9090
    - name: https
      port: 9443
  selector:
    app: console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  labels:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/name: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
        app.kubernetes.io/instance: minio-operator-console
        app.kubernetes.io/name: operator
    spec:
      containers:
        - args:
            - ui
            - --certs-dir=/tmp/certs
          image: minio/operator:v5.0.15
          imagePullPolicy: IfNotPresent
          name: console
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 9443
              name: https
          volumeMounts:
            - mountPath: /tmp/certs
              name: tls-certificates
            - mountPath: /tmp/certs/CAs
              name: tmp
      volumes:
        - name: tls-certificates
          projected:
            sources:
              - secret:
                  items:
                    - key: public.crt
                      path: public.crt
                    - key: public.crt
                      path: CAs/public.crt
                    - key: private.key
                      path: private.key
                    - key: tls.crt
                      path: tls.crt
                    - key: tls.crt
                      path: CAs/tls.crt
                    - key: tls.key
                      path: tls.key
                  name: console-tls
                  optional: true
        - name: tmp
          emptyDir: { }
      serviceAccountName: console-sa
