# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: operator-sidecar

release:
  name_template: "Version {{.Version}}"
  github:
    owner: minio
    name: operator
  extra_files:
    - glob: "*.minisig"
    - glob: "*.zip"

before:
  hooks:
    - make clean
    - go mod tidy -compat=1.21.8
    - go mod download

builds:
  - id: minio-operator-sidecar
    goos:
      - linux
    goarch:
      - arm64
      - amd64
      - ppc64le
      - s390x
    env:
      - CGO_ENABLED=0
    binary: minio-operator-sidecar
    main: ./cmd/sidecar/
    ldflags:
      - -s -w -X github.com/minio/operator/pkg.ReleaseTag={{.Tag}} -X github.com/minio/operator/pkg.CommitID={{.FullCommit}} -X github.com/minio/operator/sidecar/pkg.Version={{.Version}} -X github.com/minio/operator/sidecar/pkg.ShortCommitID={{.ShortCommit}} -X github.com/minio/operator/pkg.ReleaseTime={{.Date}}
    flags:
      - -trimpath

archives:
  - allow_different_binary_count: true
    format: binary

dockers:
  - image_templates:
      - "minio/operator-sidecar:{{ .Tag }}-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile
    extra_files:
      - LICENSE
      - CREDITS
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=TAG={{ .Tag }}"
  - image_templates:
      - "minio/operator-sidecar:{{ .Tag }}-ppc64le"
    use: buildx
    dockerfile: Dockerfile
    goarch: ppc64le
    extra_files:
      - LICENSE
      - CREDITS
    build_flag_templates:
      - "--platform=linux/ppc64le"
      - "--build-arg=TAG={{ .Tag }}"
  - image_templates:
      - "minio/operator-sidecar:{{ .Tag }}-s390x"
    use: buildx
    goarch: s390x
    dockerfile: Dockerfile
    extra_files:
      - LICENSE
      - CREDITS
    build_flag_templates:
      - "--platform=linux/s390x"
      - "--build-arg=TAG={{ .Tag }}"
  - image_templates:
      - "minio/operator-sidecar:{{ .Tag }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    extra_files:
      - LICENSE
      - CREDITS
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=TAG={{ .Tag }}"
  - image_templates:
      - "quay.io/minio/operator-sidecar:{{ .Tag }}-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile
    extra_files:
      - LICENSE
      - CREDITS
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=TAG={{ .Tag }}"
  - image_templates:
      - "quay.io/minio/operator-sidecar:{{ .Tag }}-ppc64le"
    use: buildx
    dockerfile: Dockerfile
    goarch: ppc64le
    extra_files:
      - LICENSE
      - CREDITS
    build_flag_templates:
      - "--platform=linux/ppc64le"
      - "--build-arg=TAG={{ .Tag }}"
  - image_templates:
      - "quay.io/minio/operator-sidecar:{{ .Tag }}-s390x"
    use: buildx
    goarch: s390x
    dockerfile: Dockerfile
    extra_files:
      - LICENSE
      - CREDITS
    build_flag_templates:
      - "--platform=linux/s390x"
      - "--build-arg=TAG={{ .Tag }}"
  - image_templates:
      - "quay.io/minio/operator-sidecar:{{ .Tag }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    extra_files:
      - LICENSE
      - CREDITS
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=TAG={{ .Tag }}"
docker_manifests:
  - name_template: minio/operator-sidecar:{{ .Tag }}
    image_templates:
      - minio/operator-sidecar:{{ .Tag }}-amd64
      - minio/operator-sidecar:{{ .Tag }}-arm64
      - minio/operator-sidecar:{{ .Tag }}-ppc64le
      - minio/operator-sidecar:{{ .Tag }}-s390x
  - name_template: quay.io/minio/operator-sidecar:{{ .Tag }}
    image_templates:
      - quay.io/minio/operator-sidecar:{{ .Tag }}-amd64
      - quay.io/minio/operator-sidecar:{{ .Tag }}-arm64
      - quay.io/minio/operator-sidecar:{{ .Tag }}-ppc64le
      - quay.io/minio/operator-sidecar:{{ .Tag }}-s390x
