kind: ServiceAccount
apiVersion: v1
metadata:
  namespace:  tenant-kms-encrypted
  # This should be the service account which was created in `kes-service-account.yaml`
  # Please refer https://cloud.google.com/anthos/fleet-management/docs/use-workload-identity#impersonate_a_service_account to know how
  # this service account is authorized to use GCP workload identity
  name: <SERVICE_ACCOUNT>
automountServiceAccountToken: false
