apiVersion: v1
kind: Service
metadata:
  annotations:
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/name: operator
    name: console
  name: console
spec:
  ports:
  - name: http
    port: 9090
    targetPort: 0
  - name: https
    port: 9443
    targetPort: 0
  selector:
    app: console
status:
  loadBalancer: {}
