apiVersion: v1
kind: Service
metadata:
  annotations:
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
    service.beta.openshift.io/serving-cert-secret-name: operator-tls
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/name: operator
    name: minio-operator
  name: operator
spec:
  ports:
  - name: http
    port: 4221
    targetPort: 0
  selector:
    name: minio-operator
    operator: leader
  type: ClusterIP
status:
  loadBalancer: {}
