apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: operator-tls
  creationTimestamp: null
  labels:
    name: minio-operator
  name: sts
spec:
  ports:
  - name: https
    port: 4223
    targetPort: 4223
  selector:
    name: minio-operator
  type: ClusterIP
status:
  loadBalancer: {}
