apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenants.minio.min.io
spec:
  preserveUnknownFields: false
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: [ "v1", "v2" ]
      clientConfig:
        service:
          name: operator
          namespace: minio-operator
          port: 4222
          path: /webhook/v1/crd-conversion
