// This file is part of MinIO Operator
// Copyright (c) 2021 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	miniojobsminiov1alpha1 "github.com/minio/operator/pkg/apis/miniojobs.min.io/v1alpha1"
	time "time"


	versioned "github.com/minio/operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/minio/operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/minio/operator/pkg/client/listers/miniojobs.min.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// mcInformer provides access to a shared informer and lister for
// mc.
type MinIOJobsInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MinIOJobsLister
}

type minIOJobsInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMinIOJobsInformer constructs a new informer for MC type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMinIOJobsInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMinIOJobsInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMCInformer constructs a new informer for MC type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMinIOJobsInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MinIOJobsV1alpha1().MinIOJobs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MinIOJobsV1alpha1().MinIOJobs(namespace).Watch(context.TODO(), options)
			},
		},
		&miniojobsminiov1alpha1.MinIOJobs{},
		resyncPeriod,
		indexers,
	)
}

func (f *minIOJobsInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMinIOJobsInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *minIOJobsInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&miniojobsminiov1alpha1.MinIOJobs{}, f.defaultInformer)
}

func (f *minIOJobsInformer) Lister() v1alpha1.MinIOJobsLister {
	return v1alpha1.NewMinIOJobsLister(f.Informer().GetIndexer())
}
