apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../sts-app

images:
  - name: miniodev/operator-sts-example
    newTag: aws-sdk-python

patchesJson6902:
  - target:
      group: batch
      version: v1
      kind: Job
      name: sts-example-job
    patch: |
      - op: replace
        path: /metadata/name
        value: sts-client-example-aws-sdk-python-job