// This file is part of MinIO Operator
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2

// ExposeServicesApplyConfiguration represents an declarative configuration of the ExposeServices type for use
// with apply.
type ExposeServicesApplyConfiguration struct {
	MinIO   *bool `json:"minio,omitempty"`
	Console *bool `json:"console,omitempty"`
}

// ExposeServicesApplyConfiguration constructs an declarative configuration of the ExposeServices type for use with
// apply.
func ExposeServices() *ExposeServicesApplyConfiguration {
	return &ExposeServicesApplyConfiguration{}
}

// WithMinIO sets the MinIO field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinIO field is set to the value of the last call.
func (b *ExposeServicesApplyConfiguration) WithMinIO(value bool) *ExposeServicesApplyConfiguration {
	b.MinIO = &value
	return b
}

// WithConsole sets the Console field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Console field is set to the value of the last call.
func (b *ExposeServicesApplyConfiguration) WithConsole(value bool) *ExposeServicesApplyConfiguration {
	b.Console = &value
	return b
}
