// This file is part of MinIO Operator
// Copyright (c) 2021 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2

import (
	v1 "k8s.io/api/core/v1"
)

// PrometheusConfigApplyConfiguration represents an declarative configuration of the PrometheusConfig type for use
// with apply.
type PrometheusConfigApplyConfiguration struct {
	Image                     *string                       `json:"image,omitempty"`
	SideCarImage              *string                       `json:"sidecarimage,omitempty"`
	InitImage                 *string                       `json:"initimage,omitempty"`
	DiskCapacityDB            *int                          `json:"diskCapacityGB,omitempty"`
	StorageClassName          *string                       `json:"storageClassName,omitempty"`
	Annotations               map[string]string             `json:"annotations,omitempty"`
	Labels                    map[string]string             `json:"labels,omitempty"`
	NodeSelector              map[string]string             `json:"nodeSelector,omitempty"`
	Affinity                  *v1.Affinity                  `json:"affinity,omitempty"`
	Tolerations               []v1.Toleration               `json:"tolerations,omitempty"`
	TopologySpreadConstraints []v1.TopologySpreadConstraint `json:"topologySpreadConstraints,omitempty"`
	Resources                 *v1.ResourceRequirements      `json:"resources,omitempty"`
	SecurityContext           *v1.PodSecurityContext        `json:"securityContext,omitempty"`
	ServiceAccountName        *string                       `json:"serviceAccountName,omitempty"`
	Env                       []v1.EnvVar                   `json:"env,omitempty"`
}

// PrometheusConfigApplyConfiguration constructs an declarative configuration of the PrometheusConfig type for use with
// apply.
func PrometheusConfig() *PrometheusConfigApplyConfiguration {
	return &PrometheusConfigApplyConfiguration{}
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *PrometheusConfigApplyConfiguration) WithImage(value string) *PrometheusConfigApplyConfiguration {
	b.Image = &value
	return b
}

// WithSideCarImage sets the SideCarImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SideCarImage field is set to the value of the last call.
func (b *PrometheusConfigApplyConfiguration) WithSideCarImage(value string) *PrometheusConfigApplyConfiguration {
	b.SideCarImage = &value
	return b
}

// WithInitImage sets the InitImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitImage field is set to the value of the last call.
func (b *PrometheusConfigApplyConfiguration) WithInitImage(value string) *PrometheusConfigApplyConfiguration {
	b.InitImage = &value
	return b
}

// WithDiskCapacityDB sets the DiskCapacityDB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskCapacityDB field is set to the value of the last call.
func (b *PrometheusConfigApplyConfiguration) WithDiskCapacityDB(value int) *PrometheusConfigApplyConfiguration {
	b.DiskCapacityDB = &value
	return b
}

// WithStorageClassName sets the StorageClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageClassName field is set to the value of the last call.
func (b *PrometheusConfigApplyConfiguration) WithStorageClassName(value string) *PrometheusConfigApplyConfiguration {
	b.StorageClassName = &value
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *PrometheusConfigApplyConfiguration) WithAnnotations(entries map[string]string) *PrometheusConfigApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *PrometheusConfigApplyConfiguration) WithLabels(entries map[string]string) *PrometheusConfigApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *PrometheusConfigApplyConfiguration) WithNodeSelector(entries map[string]string) *PrometheusConfigApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *PrometheusConfigApplyConfiguration) WithAffinity(value v1.Affinity) *PrometheusConfigApplyConfiguration {
	b.Affinity = &value
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *PrometheusConfigApplyConfiguration) WithTolerations(values ...v1.Toleration) *PrometheusConfigApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}

// WithTopologySpreadConstraints adds the given value to the TopologySpreadConstraints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TopologySpreadConstraints field.
func (b *PrometheusConfigApplyConfiguration) WithTopologySpreadConstraints(values ...v1.TopologySpreadConstraint) *PrometheusConfigApplyConfiguration {
	for i := range values {
		b.TopologySpreadConstraints = append(b.TopologySpreadConstraints, values[i])
	}
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *PrometheusConfigApplyConfiguration) WithResources(value v1.ResourceRequirements) *PrometheusConfigApplyConfiguration {
	b.Resources = &value
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *PrometheusConfigApplyConfiguration) WithSecurityContext(value v1.PodSecurityContext) *PrometheusConfigApplyConfiguration {
	b.SecurityContext = &value
	return b
}

// WithServiceAccountName sets the ServiceAccountName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountName field is set to the value of the last call.
func (b *PrometheusConfigApplyConfiguration) WithServiceAccountName(value string) *PrometheusConfigApplyConfiguration {
	b.ServiceAccountName = &value
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *PrometheusConfigApplyConfiguration) WithEnv(values ...v1.EnvVar) *PrometheusConfigApplyConfiguration {
	for i := range values {
		b.Env = append(b.Env, values[i])
	}
	return b
}
