// This file is part of MinIO Operator
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2

// TenantDomainsApplyConfiguration represents an declarative configuration of the TenantDomains type for use
// with apply.
type TenantDomainsApplyConfiguration struct {
	Minio   []string `json:"minio,omitempty"`
	Console *string  `json:"console,omitempty"`
}

// TenantDomainsApplyConfiguration constructs an declarative configuration of the TenantDomains type for use with
// apply.
func TenantDomains() *TenantDomainsApplyConfiguration {
	return &TenantDomainsApplyConfiguration{}
}

// WithMinio adds the given value to the Minio field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Minio field.
func (b *TenantDomainsApplyConfiguration) WithMinio(values ...string) *TenantDomainsApplyConfiguration {
	for i := range values {
		b.Minio = append(b.Minio, values[i])
	}
	return b
}

// WithConsole sets the Console field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Console field is set to the value of the last call.
func (b *TenantDomainsApplyConfiguration) WithConsole(value string) *TenantDomainsApplyConfiguration {
	b.Console = &value
	return b
}
