apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tenant-certmanager-2-cert
  namespace: tenant-certmanager
spec:
  dnsNames:
    - "minio.tenant-certmanager"
    - "minio.tenant-certmanager.svc"
    - "*.tenant-certmanager.svc.cluster.local"
    - "*.myminio.tenant-certmanager.svc.cluster.local"
    - "*.myminio-hl.tenant-certmanager.svc.cluster.local"
  secretName: tenant-certmanager-2-tls
  issuerRef:
    name: tenant-certmanager-issuer
