---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: tenant-certmanager
  labels:
    name: vault
spec:
  ports:
    - port: 8200
      name: http
  selector:
    app: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: tenant-certmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vault:1.13.3
          imagePullPolicy: "IfNotPresent"
          env:
            - name: SECRET_SHARES
              value: "5"
            - name: SECRET_THRESHOLD
              value: "3"
            - name: SELF_SIGNED_CERT
              value: "true"
            - name: TOTAL_INIT_RETRIES
              value: "5"
          ports:
            - containerPort: 8200
              name: http
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
