apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
type: Opaque
data:
  accesskey: bWluaW8= # base 64 encoded "minio" (echo -n 'minio' | base64)
  secretkey: bWluaW8xMjM= # based 64 encoded "minio123" (echo -n 'minio123' | base64)
---
apiVersion: v1
kind: Secret
metadata:
  name: mcs-secret
type: Opaque
data:
  MCS_HMAC_JWT_SECRET: WU9VUkpXVFNJR05JTkdTRUNSRVQ= # base 64 encoded "YOURJWTSIGNINGSECRET" (echo -n 'YOURJWTSIGNINGSECRET' | base64)
  MCS_PBKDF_PASSPHRASE: U0VDUkVU # base 64 encoded "SECRET" (echo -n 'SECRET' | base64)
  MCS_PBKDF_SALT: U0VDUkVU # base 64 encoded "SECRET" (echo -n 'SECRET' | base64)
  MCS_ACCESS_KEY: WU9VUk1DU0FDQ0VTUw== # base 64 encoded "YOURMCSACCESS" (echo -n 'YOURMCSACCESS' | base64)
  MCS_SECRET_KEY: WU9VUk1DU1NFQ1JFVA== # base 64 encoded "YOURMCSSECRET" (echo -n 'YOURMCSSECRET' | base64)
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      # nodePort: 30007
  selector:
    app: minio
---
apiVersion: operator.min.io/v1
kind: MinIOInstance
metadata:
  name: minio
## If specified, MinIOInstance pods will be dispatched by specified scheduler.
## If not specified, the pod will be dispatched by default scheduler.
# scheduler:
#  name: my-custom-scheduler
spec:
  ## Add metadata to the all pods created by the StatefulSet
  metadata:
    labels:
      app: minio
    annotations:
      prometheus.io/path: /minio/prometheus/metrics
      prometheus.io/port: "9000"
      prometheus.io/scrape: "true"
  ## Registry location and Tag to download MinIO Server image
  image: minio/minio:RELEASE.2020-06-18T02-23-35Z
  ## A ClusterIP Service will be created with the given name
  serviceName: minio-internal-service
  ## Secret with credentials to be used by MinIO instance.
  credsSecret:
    name: minio-creds-secret
  zones:
    - name: "zone-0"
      ## Number of MinIO servers/pods in this zone.
      ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
      ## Note that the operator does not support upgrading from standalone to distributed mode.
      servers: 4
  ## Supply number of volumes to be mounted per MinIO server instance.
  volumesPerServer: 4
  ## Mount path where PV will be mounted inside container(s). Defaults to "/export".
  mountPath: /export
  ## Sub path inside Mount path where MinIO starts. Defaults to "".
  # subPath: /data
  ## This VolumeClaimTemplate is used across all the volumes provisioned for MinIO cluster.
  ## Please do not change the volumeClaimTemplate field while expanding the cluster, this may
  ## lead to unbound PVCs and missing data
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Ti
  ## Define configuration for MCS (Graphical user interface for MinIO)
  mcs:
    image: minio/mcs:v0.1.0
    replicas: 2
    mcsSecret:
      name: mcs-secret
    metadata:
      labels:
        app: mcs
  ## Secret with certificates to configure TLS for MinIO certs. Create secrets as explained
  ## here: https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
  # externalCertSecret:
  # name: tls-ssl-minio
  ## Enable Kubernetes based certificate generation and signing as explained in
  ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
  requestAutoCert: true
  ## PodManagement policy for pods created by StatefulSet. Can be "OrderedReady" or "Parallel"
  ## Refer https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy
  ## for details. Defaults to "Parallel"
  ## If set to "OrderedReady", then disable Readiness checks below. Readiness check will only
  ## work if PodManagementPolicy is set to "Parallel".
  podManagementPolicy: Parallel
  ## Used when "requestAutoCert" is set to true. Set CommonName for the auto-generated certificate.
  ## Internal DNS name for the pod will be used if CommonName is not provided.
  ## DNS name format is minio-{0...3}.minio.default.svc.cluster.local
  certConfig:
    commonName: ""
    organizationName: []
    dnsNames: []
  ## Used to specify a toleration for a pod
  # tolerations:
  #  - effect: NoSchedule
  #    key: dedicated
  #    operator: Equal
  #    value: storage
  ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
  # env:
    # - name: MINIO_BROWSER
    #  value: "off" # to turn-off browser
    # - name: MINIO_STORAGE_CLASS_STANDARD
    #   value: "EC:4"
  ## Configure resource requests and limits for MinIO containers
  # resources:
    # requests:
      # memory: 20Gi
  ## Liveness probe detects situations where MinIO server instance
  ## is not working properly and needs restart. Kubernetes automatically
  ## restarts the pods if liveness checks fail.
  liveness:
    initialDelaySeconds: 1
    periodSeconds: 1
    timeoutSeconds: 60 # should always greater than MINIO_API_READY_DEADLINE (which defaults to 10s)
  ## Readiness probe detects situations when MinIO server instance
  ## is not ready to accept traffic. Kubernetes doesn't forward
  ## traffic to the pod while readiness checks fail.
  ## Readiness check will only work if PodManagementPolicy is set to "Parallel".
  ## Disable this check if you're setting PodManagementPolicy to "OrderedReady".
  readiness:
    initialDelaySeconds: 1
    periodSeconds: 1
    timeoutSeconds: 60
  ## nodeSelector parameters for MinIO Pods. It specifies a map of key-value pairs. For the pod to be
  ## eligible to run on a node, the node must have each of the
  ## indicated key-value pairs as labels.
  ## Read more here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  # nodeSelector:
  #   disktype: ssd
  ## Affinity settings for MinIO pods. Read more about affinity
  ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
  # affinity:
