apiVersion: operator.min.io/v1
kind: MinIOInstance
metadata:
  name: minio
spec:
  zones:
    - name: "zone-0"
      ## Number of MinIO servers/pods in this zone.
      servers: 4
    - name: "zone-1"
      ## Number of MinIO servers/pods in this zone.
      servers: 4
