apiVersion: v2
description: A Helm chart for MinIO Operator
name: minio-operator
version: 4.2.7
appVersion: v4.2.7
keywords:
- storage
- object-storage
- S3
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/operator
maintainers:
- name: MinIO, Inc
  email: dev@minio.io
type: application
