// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Operator
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package operator_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/operator/models"
)

// TenantDetailsOKCode is the HTTP code returned for type TenantDetailsOK
const TenantDetailsOKCode int = 200

/*
TenantDetailsOK A successful response.

swagger:response tenantDetailsOK
*/
type TenantDetailsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Tenant `json:"body,omitempty"`
}

// NewTenantDetailsOK creates TenantDetailsOK with default headers values
func NewTenantDetailsOK() *TenantDetailsOK {

	return &TenantDetailsOK{}
}

// WithPayload adds the payload to the tenant details o k response
func (o *TenantDetailsOK) WithPayload(payload *models.Tenant) *TenantDetailsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the tenant details o k response
func (o *TenantDetailsOK) SetPayload(payload *models.Tenant) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TenantDetailsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
TenantDetailsDefault Generic error response.

swagger:response tenantDetailsDefault
*/
type TenantDetailsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewTenantDetailsDefault creates TenantDetailsDefault with default headers values
func NewTenantDetailsDefault(code int) *TenantDetailsDefault {
	if code <= 0 {
		code = 500
	}

	return &TenantDetailsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the tenant details default response
func (o *TenantDetailsDefault) WithStatusCode(code int) *TenantDetailsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the tenant details default response
func (o *TenantDetailsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the tenant details default response
func (o *TenantDetailsDefault) WithPayload(payload *models.Error) *TenantDetailsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the tenant details default response
func (o *TenantDetailsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TenantDetailsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
