apiVersion: v1
kind: Secret
metadata:
  name: init-kes-configuration
  namespace: minio-tenant
type: Opaque
stringData:
  init-config.yaml: |-
    version: "v1"
    address: 0.0.0.0:7373
    tls:
      key: /tmp/stateful-kes/server.key
      cert: /tmp/stateful-kes/server.crt
      client:
        verify_cert: false

    system:
      admin:
        identity: ${MINIO_STATEFUL_KES_SYS_ADMIN_IDENTITY}

    unseal:
      environment:
        name: KES_UNSEAL_KEY

    enclave:
      default:
        admin:
          identity: ${MINIO_STATEFUL_KES_ENCLAVE_ADMIN_IDENTITY}
        policy:
          minio:
            allow:
            - /v1/api
            - /v1/log/audit
            - /v1/log/error
            - /v1/key/create/*
            - /v1/key/generate/*
            - /v1/key/decrypt/*
            identities:
            - ${MINIO_STATEFUL_KES_IDENTITY}
