{{- if eq .Values.operator.scope "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-operator-binding
  namespace: {{ .Release.Namespace }}
  labels: {{- include "minio-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minio-operator-role
subjects:
  - kind: ServiceAccount
    name: minio-operator
    namespace: {{ .Release.Namespace }}
{{- end }} 