apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.16.0+git
    operators.operatorframework.io/project_layout: unknown
  name: minio-operator.v4.4.7
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Tenant
      name: tenants.minio.min.io
      version: v1
    - kind: Tenant
      name: tenants.minio.min.io
      version: v2
  description: Minio Operator description. TODO.
  displayName: Minio Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - watch
          - create
          - list
          - patch
          - update
          - deletecollection
        - apiGroups:
          - ""
          resources:
          - namespaces
          - services
          - events
          - resourcequotas
          - nodes
          verbs:
          - get
          - watch
          - create
          - list
          - patch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - watch
          - create
          - list
          - patch
          - delete
          - deletecollection
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - deletecollection
          - list
          - get
          - watch
          - update
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
          - watch
          - create
          - list
          - patch
        - apiGroups:
          - apps
          resources:
          - statefulsets
          - deployments
          verbs:
          - get
          - create
          - list
          - patch
          - watch
          - update
          - delete
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - get
          - create
          - list
          - patch
          - watch
          - update
          - delete
        - apiGroups:
          - certificates.k8s.io
          resources:
          - certificatesigningrequests
          - certificatesigningrequests/approval
          - certificatesigningrequests/status
          verbs:
          - update
          - create
          - get
        - apiGroups:
          - minio.min.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - min.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          verbs:
          - get
          - list
          - watch
          - create
          - delete
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - list
          - watch
          - update
          - patch
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshots
          verbs:
          - get
          - list
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotcontents
          verbs:
          - get
          - list
        - apiGroups:
          - storage.k8s.io
          resources:
          - csinodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - storage.k8s.io
          resources:
          - volumeattachments
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - endpoints
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - direct.csi.min.io
          resources:
          - volumes
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - direct.csi.min.io
          resources:
          - directcsidrives
          - directcsivolumes
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - ""
          resources:
          - pod
          - pods/log
          verbs:
          - get
          - list
          - watch
        serviceAccountName: console-sa
      - rules:
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - update
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - get
          - update
          - list
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - watch
          - list
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - events
          - configmaps
          verbs:
          - get
          - watch
          - create
          - list
          - delete
          - deletecollection
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - watch
          - create
          - update
          - list
          - delete
          - deletecollection
        - apiGroups:
          - apps
          resources:
          - statefulsets
          - deployments
          - deployments/finalizers
          verbs:
          - get
          - create
          - list
          - patch
          - watch
          - update
          - delete
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - get
          - create
          - list
          - patch
          - watch
          - update
          - delete
        - apiGroups:
          - certificates.k8s.io
          resources:
          - certificatesigningrequests
          - certificatesigningrequests/approval
          - certificatesigningrequests/status
          verbs:
          - update
          - create
          - get
          - delete
        - apiGroups:
          - certificates.k8s.io
          resourceNames:
          - kubernetes.io/legacy-unknown
          - kubernetes.io/kube-apiserver-client
          - kubernetes.io/kubelet-serving
          resources:
          - signers
          verbs:
          - approve
          - sign
        - apiGroups:
          - minio.min.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - min.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - prometheuses
          verbs:
          - '*'
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - update
          - create
        serviceAccountName: minio-operator
      deployments:
      - name: console
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: console
          strategy: {}
          template:
            metadata:
              labels:
                app: console
            spec:
              containers:
              - args:
                - server
                env:
                - name: CONSOLE_OPERATOR_MODE
                  value: "on"
                image: minio/console:v0.14.2
                imagePullPolicy: IfNotPresent
                name: console
                ports:
                - containerPort: 9090
                  name: http
                - containerPort: 9433
                  name: https
                resources: {}
                securityContext:
                  runAsGroup: 1000
                  runAsNonRoot: true
                  runAsUser: 1000
              serviceAccountName: console-sa
      - name: minio-operator
        spec:
          replicas: 2
          selector:
            matchLabels:
              name: minio-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: minio-operator
            spec:
              affinity:
                podAntiAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                      - key: name
                        operator: In
                        values:
                        - minio-operator
                    topologyKey: kubernetes.io/hostname
              containers:
              - image: minio/operator:v4.4.7
                imagePullPolicy: IfNotPresent
                name: minio-operator
                resources:
                  requests:
                    cpu: 200m
                    ephemeral-storage: 500Mi
                    memory: 256Mi
                securityContext:
                  runAsGroup: 1000
                  runAsNonRoot: true
                  runAsUser: 1000
              serviceAccountName: minio-operator
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - minio-operator
  links:
  - name: Minio Operator
    url: https://minio-operator.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 4.4.7
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    - v2
    containerPort: 4222
    conversionCRDs:
    - tenants.minio.min.io
    deploymentName: operator
    generateName: ctenants.kb.io
    sideEffects: None
    targetPort: 0
    type: ConversionWebhook
    webhookPath: /webhook/v1/crd-conversion
