apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  template:
    spec:
      containers:
        - name: minio-operator
          env:
            - name: MINIO_CONSOLE_TLS_ENABLE
              value: "off"
            - name: OPERATOR_STS_AUTO_TLS_ENABLED
              value: "off"
            - name: OPERATOR_STS_ENABLED
              value: "on"
