apiVersion: v2
description: A Helm chart for MinIO Operator
name: operator
version: 7.1.1
appVersion: v7.1.1
keywords:
  - storage
  - object-storage
  - S3
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
  - https://github.com/minio/operator
maintainers:
  - name: MinIO, Inc
    email: dev@minio.io
type: application
