// This file is part of MinIO Console Server
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/minio/minio-operator/pkg/apis/operator.min.io/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MinIOInstanceLister helps list MinIOInstances.
// All objects returned here must be treated as read-only.
type MinIOInstanceLister interface {
	// List lists all MinIOInstances in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MinIOInstance, err error)
	// MinIOInstances returns an object that can list and get MinIOInstances.
	MinIOInstances(namespace string) MinIOInstanceNamespaceLister
	MinIOInstanceListerExpansion
}

// minIOInstanceLister implements the MinIOInstanceLister interface.
type minIOInstanceLister struct {
	indexer cache.Indexer
}

// NewMinIOInstanceLister returns a new MinIOInstanceLister.
func NewMinIOInstanceLister(indexer cache.Indexer) MinIOInstanceLister {
	return &minIOInstanceLister{indexer: indexer}
}

// List lists all MinIOInstances in the indexer.
func (s *minIOInstanceLister) List(selector labels.Selector) (ret []*v1.MinIOInstance, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.MinIOInstance))
	})
	return ret, err
}

// MinIOInstances returns an object that can list and get MinIOInstances.
func (s *minIOInstanceLister) MinIOInstances(namespace string) MinIOInstanceNamespaceLister {
	return minIOInstanceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MinIOInstanceNamespaceLister helps list and get MinIOInstances.
// All objects returned here must be treated as read-only.
type MinIOInstanceNamespaceLister interface {
	// List lists all MinIOInstances in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MinIOInstance, err error)
	// Get retrieves the MinIOInstance from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.MinIOInstance, error)
	MinIOInstanceNamespaceListerExpansion
}

// minIOInstanceNamespaceLister implements the MinIOInstanceNamespaceLister
// interface.
type minIOInstanceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MinIOInstances in the indexer for a given namespace.
func (s minIOInstanceNamespaceLister) List(selector labels.Selector) (ret []*v1.MinIOInstance, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.MinIOInstance))
	})
	return ret, err
}

// Get retrieves the MinIOInstance from the indexer for a given namespace and name.
func (s minIOInstanceNamespaceLister) Get(name string) (*v1.MinIOInstance, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("minioinstance"), name)
	}
	return obj.(*v1.MinIOInstance), nil
}
