apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tenant-certmanager-ca-certificate
  namespace: tenant-certmanager
spec:
  isCA: true
  commonName: tenant-certmanager-ca
  secretName: tenant-certmanager-ca-tls
  duration: 70128h # 8y
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
    group: cert-manager.io
