apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tenant-certmanager-cert
  namespace: tenant-certmanager
spec:
  # If you see "Empty issuer DN not allowed in X509Certificates"
  # You will need to add spec.subject.organizations or spec.commonName
  # As documented in https://cert-manager.io/docs/usage/certificate/
  # This specially if your other apps can't trust MinIO cert issued by cert-manager
  # Example
  #
  # subject:
  #   organizations:
  #     - jetstack
  # commonName: example.com
  dnsNames:
    - "minio.tenant-certmanager"
    - "minio.tenant-certmanager.svc"
    - "minio.tenant-certmanager.svc.cluster.local"
    - "*.myminio-hl.tenant-certmanager.svc.cluster.local"
    - "*.tenant-certmanager.svc.cluster.local"
    - "*.myminio.tenant-certmanager.svc.cluster.local"
  secretName: myminio-tls
  issuerRef:
    name: tenant-certmanager-issuer
