name: goreleaser

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'release*'
      - 'master'

jobs:
  goreleaser:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up swagger
        run: |
          go install github.com/go-swagger/go-swagger/cmd/swagger@latest
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --skip-publish --clean --snapshot
